In [1]:
import torch
# nn: NeuralNetwork

In [2]:
class MyModule(torch.nn.Module):
    def __init__(self):
        """
        定义模型的初始化参数、方法
        """
        super(MyModule, self).__init__()

    def forward(self, input):
        """
        向前传播
        :param input:
        :return:
        """
        output = input + 1
        return output


demo = MyModule()
x = torch.tensor(1.)
demo(x)

tensor(2.)

In [3]:
input = torch.tensor([
    [1, 2, 0, 3, 1],
    [0, 1, 2, 3, 1],
    [1, 2, 1, 0, 0],
    [5, 2, 3, 1, 1],
    [2, 1, 0, 1, 1]
])
input

tensor([[1, 2, 0, 3, 1],
        [0, 1, 2, 3, 1],
        [1, 2, 1, 0, 0],
        [5, 2, 3, 1, 1],
        [2, 1, 0, 1, 1]])

In [4]:
kernel = torch.tensor([
    [1, 2, 1],
    [0, 1, 0],
    [2, 1, 0]
])

In [5]:
input.shape, kernel.shape

(torch.Size([5, 5]), torch.Size([3, 3]))

In [15]:
# 输入矩阵与卷积核的shape改造为符合卷积神经网络输入的格式
# 官方文档将其定义为：input – input tensor of shape (minibatch, in_channels, iH,iW)
# 想想也确实是这么个理，神经网络主要应用与图像处理，对于一个512×512大小的RGB三通道图片，其形状为3×512×512。如果使用DataLoader读取文件，batch_size=64，那么其输入矩阵形状为64×3×512×512
input = torch.reshape(input, (-1, 1, 5, 5))
kernel = torch.reshape(kernel, (-1, 1, 3, 3))
input.shape, kernel.shape

(torch.Size([1, 1, 5, 5]), torch.Size([1, 1, 3, 3]))

In [17]:
import torch.nn.functional as F

F.conv2d(input, kernel)
# 对于一个5×5的矩阵，卷积核步长设置为1，使用3×3的卷积核完成一次卷积后的结果是3×3；

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])

In [18]:
F.conv2d(input, kernel, stride=2)
# 对于一个5×5的矩阵，卷积核步长stride设置为2，使用3×3的卷积核完成一次卷积后的结果是2×2.

tensor([[[[10, 12],
          [13,  3]]]])

In [23]:
# padding=1参数为输入矩阵的上下左右周围添加了一圈为0的值，输入矩阵变成了7×7，如下面的input_pad_1所示
F.conv2d(input, kernel, padding=1)

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])

In [24]:
input_pad_1 = torch.tensor([
    [0 for i in range(7)],
    [0, 1, 2, 0, 3, 1, 0],
    [0, 0, 1, 2, 3, 1, 0],
    [0, 1, 2, 1, 0, 0, 0],
    [0, 5, 2, 3, 1, 1, 0],
    [0, 2, 1, 0, 1, 1, 0],
    [0 for i in range(7)]
])
input_pad_1

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 2, 0, 3, 1, 0],
        [0, 0, 1, 2, 3, 1, 0],
        [0, 1, 2, 1, 0, 0, 0],
        [0, 5, 2, 3, 1, 1, 0],
        [0, 2, 1, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0]])

In [26]:
input_pad_1 = torch.reshape(input_pad_1, (-1, 1, 7, 7))
F.conv2d(input_pad_1, kernel)
# 可以看到这里的输出结果与F.conv2d(input, kernel, padding=1)是一模一样的

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])