In [1]:
import torch

## 2.2.1 创建Tensor

In [2]:
x = torch.empty(5, 3)  # 创建一个未初始化的Tensor
print(x)

tensor([[-2.7484e-14,  8.2817e-43, -2.7484e-14],
        [ 8.2817e-43, -2.7484e-14,  8.2817e-43],
        [-2.7484e-14,  8.2817e-43, -2.7484e-14],
        [ 8.2817e-43, -2.7484e-14,  8.2817e-43],
        [-2.7484e-14,  8.2817e-43, -2.7484e-14]])


In [3]:
x = torch.rand(5, 3)  # 创建一个5x3的随机初始化Tensor
print(x)

tensor([[0.4030, 0.2349, 0.2513],
        [0.0750, 0.2805, 0.6088],
        [0.0777, 0.9726, 0.8226],
        [0.9853, 0.6568, 0.3863],
        [0.0476, 0.4200, 0.9507]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)  # 创建一个5x3的long型全0的Tensor
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])  # 还可以直接根据数据创建
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 还可以通过现有的Tensor来创建，此方法会默认重用输入Tensor的一些属性，例如数据类型，除非自定义数据类型。
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
torch.randn_like(x, dtype=torch.float)

tensor([[-1.4658, -0.0666, -0.2081],
        [-1.2419, -0.1888, -1.6088],
        [-0.5297, -0.9478, -0.4115],
        [ 0.6963, -1.6178,  0.3148],
        [ 0.6180,  0.0197,  0.3810]])

In [8]:
# x.shape # torch.Size([5, 3])
x.size()

torch.Size([5, 3])

## 2.2.2 操作

In [25]:
x = torch.ones(2, 3)  # 创建一个5x3全1的Tensor
y = x * 2
y

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [24]:
# x + y

# torch.add(x, y)

# result = torch.empty(5, 3)
# torch.add(x, y, out=result)

# y.add_(x)
y.add(x)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

## 索引

In [26]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
y = x[0, :]
y += 1
y

tensor([2., 2., 2.])

In [30]:
x

tensor([[2., 2., 2.],
        [1., 1., 1.]])

In [31]:
x = torch.ones(2, 3)  # 创建一个5x3全1的Tensor
y = torch.ones(2, 3)
x, y

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [33]:
m, n = x[0, :], y[0, :].copy
m, n

AttributeError: 'Tensor' object has no attribute 'copy'

## 改变形状

## 2.2.3 广播机制