In [5]:
import torch

In [6]:
# 直接输入值创建Tensor
a = torch.Tensor([[1, 2], [3, 4]])
a

tensor([[1., 2.],
        [3., 4.]])

In [7]:
a.type(), type(a)

('torch.FloatTensor', torch.Tensor)

In [11]:
# 创建指定形状的Tensor
torch.Tensor(2, 3)  # 创建一个2行3列的Tensor

tensor([[1.6894e-07, 1.0570e+21, 2.6368e-09],
        [2.5985e+20, 5.4932e-05, 2.1972e-04]])

In [12]:
b = torch.Tensor(2, 3)
b == 0

tensor([[False, False, False],
        [False, False, False]])

In [8]:
# 创建全为1的Tensor
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# 创建一个与指定Tensor形状相同的全1的Tensor
torch.ones_like(a)

tensor([[1., 1.],
        [1., 1.]])

In [9]:
# 创建全为0的Tensor
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
# 创建一个与指定Tensor形状相同的全0Tensor
torch.zeros_like(a)

tensor([[0., 0.],
        [0., 0.]])

In [17]:
# 生成一个0~1的随机值Tensor
torch.rand(2, 3)

tensor([[0.0425, 0.6559, 0.8991],
        [0.7229, 0.1844, 0.7425]])

In [14]:
torch.rand(5)

tensor([0.1991, 0.1606, 0.7864, 0.2359, 0.6833])

In [17]:
# 生成正态分布Tensor
torch.manual_seed(666)  # 随机种子

torch.normal(
    mean=0,
    std=torch.rand(5)
)

tensor([0.2884, 0.3202, 0.1066, 0.0405, 0.0553])

In [32]:
# 生成正态分布Tensor
torch.normal(
    mean=torch.rand(5),
    std=torch.rand(5)
)

tensor([-1.9788,  0.2116,  1.2325,  0.1202, -0.8043])

In [38]:
# 创建等步长的Tensor
torch.arange(0, 10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# 创建等间隔的Tensor
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [43]:
# 生成随机乱序序号
torch.randperm(10)

tensor([5, 9, 0, 3, 2, 1, 4, 6, 7, 8])

In [19]:
# 创建对角Matrix
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])