In [1]:
import torch

In [3]:
# 直接输入值创建Tensor
a = torch.Tensor([[1, 2], [3, 4]])
a

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
a.type(), type(a)  #%%
import torch

In [ ]:
# 直接输入值创建Tensor
a = torch.Tensor([[1, 2], [3, 4]])
a

In [ ]:
a.type(), type(a)

In [7]:
# 创建指定形状的Tensor
torch.Tensor(2, 3)  # 创建一个2行3列的Tensor

tensor([[1.0326e-08, 1.3119e-08, 1.7061e-07],
        [2.6822e+23, 2.1971e-04, 1.0872e-05]])

In [8]:
# 创建全为1的Tensor
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# 创建一个与指定Tensor形状相同的全1的Tensor
torch.ones_like(a)

tensor([[1., 1.],
        [1., 1.]])

In [9]:
# 创建全为0的Tensor
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
# 创建一个与指定Tensor形状相同的全0Tensor
torch.zeros_like(a)

tensor([[0., 0.],
        [0., 0.]])

In [17]:
# 生成一个0~1的随机值Tensor
torch.rand(2, 3)

tensor([[0.0425, 0.6559, 0.8991],
        [0.7229, 0.1844, 0.7425]])

In [19]:
torch.rand(5)

tensor([0.1692, 0.3414, 0.4782, 0.8589, 0.2010])

In [11]:
# 生成正态分布Tensor
torch.manual_seed(666)  # 随机种子

torch.normal(
    mean=0,
    std=torch.rand(5)
)

tensor([0.2884, 0.3202, 0.1066, 0.0405, 0.0553])

In [32]:
# 生成正态分布Tensor
torch.normal(
    mean=torch.rand(5),
    std=torch.rand(5)
)

tensor([-1.9788,  0.2116,  1.2325,  0.1202, -0.8043])

In [38]:
# 创建等步长的Tensor
torch.arange(0, 10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# 创建等间隔的Tensor
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [43]:
# 生成随机乱序序号
torch.randperm(10)

tensor([5, 9, 0, 3, 2, 1, 4, 6, 7, 8])

In [45]:
# 创建对角Matrix
torch.eye(4)

tensor([[4., 0., 0., 0.],
        [0., 4., 0., 0.],
        [0., 0., 4., 0.],
        [0., 0., 0., 4.]])