In [1]:
import torch

口 torch.where(condition, × ， y) ： 按照条件从 × 和 y 中选出满足条件的元素组成新的 te n s o r
口 torch.gather(input, dim, index, out=None): 在指定维度上按照索引赋值输出 te nso r
口 torch.index select(input, dim, index, out=None): 按照指定索引输出 tensor
口 torch.masked select(input, mask, out=None): 按照 mask 输出 tensor, 输出为向量
口 torch.take(input, indices): 将输入看成 1 D-tensor, 按照索引得到输出 tensor
口 torch.nonzero(input, out=None): 输出非 0 元素的坐标

## torch.where()

In [9]:
a = torch.arange(1, 10, 1).reshape(3, -1)
b = torch.ones_like(a) * 5

# 如果a<b，则输出a，否则输出b
torch.where(a < b, a, b)

tensor([[1, 2, 3],
        [4, 5, 5],
        [5, 5, 5]])

## torch.index_select()

In [11]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
# 在a的第0维上（按行划分），分别获取第0维上的0、2、1个元素
torch.index_select(a, dim=0, index=torch.tensor([0, 2, 1]))

tensor([[1, 2, 3],
        [7, 8, 9],
        [4, 5, 6]])

In [17]:
# 在a的第1维上（按列划分），分别获取第0维上的0、2个元素
torch.index_select(a, dim=1, index=torch.tensor([0, 2]))

tensor([[1, 3],
        [4, 6],
        [7, 9]])

## torch.gather()

In [26]:
torch.gather(
    a,
    dim=0,
    index=torch.tensor([
        [0, 1, 2],
        [0, 2, 1]
    ])
)

tensor([[1, 5, 9],
        [1, 8, 6]])

In [27]:
torch.gather(
    a,
    dim=1,
    index=torch.tensor([
        [0, 1, 2],
        [0, 2, 1]
    ])
)
# 有点难以理解，建议参考https://blog.csdn.net/guofei_fly/article/details/104184271

tensor([[1, 2, 3],
        [4, 6, 5]])

## torch.masked_select()

In [29]:
torch.gt(a, 6)

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [31]:
torch.masked_select(a, torch.gt(a, 5))

tensor([6, 7, 8, 9])

## torch.take()

In [32]:
torch.take(a, index=torch.tensor([8, 6, 3, 2, 1, 0]))

tensor([9, 7, 4, 3, 2, 1])

## torch.nonzero()

In [35]:
b = torch.eye(3)
b

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [36]:
torch.nonzero(b)

tensor([[0, 0],
        [1, 1],
        [2, 2]])