囗 torch.cat(seq, dim=0, out=None): 按照已经存在的维度进行拼接
囗 torch.stack(seq, dim=0, out=None): 按照新的维度进行拼接
囗 torch.gather(input, dim, index, out=None): 在指定维度上按照索引赋值
输出 tensor

In [1]:
import torch

In [4]:
a = torch.linspace(1, 6, 6).view(2, 3)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b = torch.zeros_like(a)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## torch.cat()

In [7]:
torch.cat((a, b), dim=0)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.cat((a, b), dim=1)

tensor([[1., 2., 3., 0., 0., 0.],
        [4., 5., 6., 0., 0., 0.]])

## torch.stack()

In [9]:
torch.stack((a, b), dim=0)

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [11]:
torch.stack((a, b), dim=0).shape

torch.Size([2, 2, 3])

In [10]:
torch.stack((a, b), dim=1)

tensor([[[1., 2., 3.],
         [0., 0., 0.]],

        [[4., 5., 6.],
         [0., 0., 0.]]])

In [12]:
torch.stack((a, b), dim=1).shape

torch.Size([2, 2, 3])

In [13]:
# 注意torch.stack()与torch.cat()的区别，torch.cat()不增加Tensor的维数，torch.stack()增加了维数