囗 torch.chunk(tensor, chunks, dim=0): 按照某个维度平均分块 （ 最
后一个可能小于平均值 ）
囗 torch.split(tensor, split size 0 r sections, dim=O) ： 按照某个维度
依照第二个参数给出的 list 或者 i nt 进行分割 tensor

In [1]:
import torch

In [33]:
a = torch.linspace(1, 16, 16).view(-1, 8)
a

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13., 14., 15., 16.]])

## torch.chunk()

In [34]:
torch.chunk(a, 2)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]),
 tensor([[ 9., 10., 11., 12., 13., 14., 15., 16.]]))

In [37]:
torch.chunk(a, 4, dim=1)

(tensor([[ 1.,  2.],
         [ 9., 10.]]),
 tensor([[ 3.,  4.],
         [11., 12.]]),
 tensor([[ 5.,  6.],
         [13., 14.]]),
 tensor([[ 7.,  8.],
         [15., 16.]]))

## torch.split()

In [22]:
torch.split(a, 2)

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 tensor([[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]))

In [39]:
torch.split(a, 4, dim=1)

(tensor([[ 1.,  2.,  3.,  4.],
         [ 9., 10., 11., 12.]]),
 tensor([[ 5.,  6.,  7.,  8.],
         [13., 14., 15., 16.]]))

In [40]:
# torch.chunk(a, 4, dim=1)中的“4”代表分为4份，torch.split(a, 4, dim=1)中的4代表每组有4个