囗 torch.reshape(input, shape)
囗 torch.t(input) ： 只针对 2 D tensor 转置
囗 torch.transpose(input, dim0, diml): 交换两个维度
囗 torch.squeeze(input, dim=None, out=None): 去除那些维度大小为 1 的
维度
囗 torch.unbind(tensor, dim=0): 去除某个维度
囗 torch.unsqueeze(input, dim, out=None): 在指定位置添加维度
囗 torch.flip(input, dims) ： 按照给定维度翻转张量
囗 torch.rot90(inputl k, dims) ： 按照指定维度和旋转次数进行张量旋转

In [1]:
import torch

## tensor.reshape()

In [3]:
a = torch.rand(2, 3)
a

tensor([[0.9319, 0.4499, 0.2324],
        [0.4293, 0.4684, 0.7465]])

In [4]:
a.shape

torch.Size([2, 3])

In [6]:
torch.reshape(a, (-1, 2))

tensor([[0.9319, 0.4499],
        [0.2324, 0.4293],
        [0.4684, 0.7465]])

## torch.t()

In [8]:
torch.t(a)

tensor([[0.9319, 0.4293],
        [0.4499, 0.4684],
        [0.2324, 0.7465]])

## torch.transpose()

In [10]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.3487, 0.0950, 0.6647, 0.3460],
         [0.9369, 0.8972, 0.0972, 0.0224],
         [0.9011, 0.7166, 0.5357, 0.1637]],

        [[0.2214, 0.3386, 0.2626, 0.6853],
         [0.6632, 0.3724, 0.8269, 0.8648],
         [0.6579, 0.5012, 0.7649, 0.9994]]])

In [11]:
b.shape

torch.Size([2, 3, 4])

In [13]:
torch.transpose(b, 0, 1)  # 交换第0、1维度

tensor([[[0.3487, 0.0950, 0.6647, 0.3460],
         [0.2214, 0.3386, 0.2626, 0.6853]],

        [[0.9369, 0.8972, 0.0972, 0.0224],
         [0.6632, 0.3724, 0.8269, 0.8648]],

        [[0.9011, 0.7166, 0.5357, 0.1637],
         [0.6579, 0.5012, 0.7649, 0.9994]]])

In [15]:
torch.transpose(b, 0, 1).shape

torch.Size([3, 2, 4])

## torch.squeeze()

In [18]:
c = torch.rand(1, 2, 3)
c

tensor([[[0.9330, 0.5412, 0.2054],
         [0.5171, 0.4289, 0.2797]]])

In [19]:
torch.squeeze(c)  # 去掉那些无用的维度（维数为1）

tensor([[0.9330, 0.5412, 0.2054],
        [0.5171, 0.4289, 0.2797]])

## torch.unsqueeze()

In [22]:
torch.unsqueeze(c, 0)  # 加上一个无用维度

tensor([[[[0.9330, 0.5412, 0.2054],
          [0.5171, 0.4289, 0.2797]]]])

## torch.unbind()

In [27]:
torch.unbind(a, dim=1)  # 将某个维度拆成一个一个的

(tensor([0.9319, 0.4293]), tensor([0.4499, 0.4684]), tensor([0.2324, 0.7465]))

## torch.flip()

In [31]:
a

tensor([[0.9319, 0.4499, 0.2324],
        [0.4293, 0.4684, 0.7465]])

In [32]:
torch.flip(a, dims=(0,1))  # 翻转哪两个维度

tensor([[0.7465, 0.4684, 0.4293],
        [0.2324, 0.4499, 0.9319]])

## torch.rot90()

In [37]:
torch.rot90(a)  # 旋转矩阵

tensor([[0.2324, 0.7465],
        [0.4499, 0.4684],
        [0.9319, 0.4293]])

In [35]:
torch.rot90(a, 2)

tensor([[0.7465, 0.4684, 0.4293],
        [0.2324, 0.4499, 0.9319]])

In [36]:
torch.rot90(a, 4)

tensor([[0.9319, 0.4499, 0.2324],
        [0.4293, 0.4684, 0.7465]])