In [1]:
import torch

In [2]:
torch.device('cpu')

device(type='cpu')

In [4]:
torch.device('cuda')

device(type='cuda')

In [6]:
device = torch.device('cuda')
torch.tensor([2, 2], device=device)

tensor([2, 2], device='cuda:0')

In [7]:
torch.tensor(
    [2, 2],
    dtype=torch.float32,
    device=device
)

tensor([2., 2.], device='cuda:0')

In [8]:
# 定义一个稀疏张量
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
v = torch.tensor([1, 2, 3])
torch.sparse_coo_tensor(i, v, (4, 4))

tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1, 2, 3]),
       size=(4, 4), nnz=3, layout=torch.sparse_coo)

In [10]:
torch.sparse_coo_tensor(i, v, (4, 4)).to_dense()

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 0]])