In [25]:
import torch

In [26]:
a = torch.tensor([2., 3., 4.])
a

tensor([2., 3., 4.])

In [27]:
b = torch.ones_like(a)
b

tensor([1., 1., 1.])

## 加法

In [28]:
a + b

tensor([3., 4., 5.])

In [29]:
torch.add(a, b)

tensor([3., 4., 5.])

In [30]:
a.add(b)

tensor([3., 4., 5.])

In [31]:
a.add_(b)  # 注意，这里执行过.add_(b)后，直接将结果赋值到了a的内存上

tensor([3., 4., 5.])

In [32]:
a

tensor([3., 4., 5.])

## 减法

In [33]:
 a - b

tensor([2., 3., 4.])

In [34]:
torch.sub(a, b)

tensor([2., 3., 4.])

In [35]:
a.sub(b)

tensor([2., 3., 4.])

In [36]:
a.sub_(b)  # 注意，这里执行过.sub_(b)后，直接将结果赋值到了a的内存上

tensor([2., 3., 4.])

In [37]:
a

tensor([2., 3., 4.])

## 乘法运算

In [38]:
# 哈达玛积(element wise, 对应元素相乘)
a * b

tensor([2., 3., 4.])

In [39]:
torch.mul(a, b)

tensor([2., 3., 4.])

In [40]:
a.mul(b)

tensor([2., 3., 4.])

In [41]:
a.mul_(b)

tensor([2., 3., 4.])

## 除法

In [42]:
a / b

tensor([2., 3., 4.])

In [43]:
torch.div(a, b)

tensor([2., 3., 4.])

In [44]:
a.div(b)

tensor([2., 3., 4.])

In [45]:
a.div_(b)

tensor([2., 3., 4.])

In [46]:
a

tensor([2., 3., 4.])

## 矩阵运算

In [51]:
# 二维矩阵乘法运算操作包括torch.mm()、torch.matmul()、@
c = torch.linspace(1, 4, 4).view(2, -1)
c

tensor([[1., 2.],
        [3., 4.]])

In [52]:
d = torch.ones_like(c)
d

tensor([[1., 1.],
        [1., 1.]])

In [53]:
torch.mm(c, d)

tensor([[3., 3.],
        [7., 7.]])

In [56]:
torch.matmul(c, d)

tensor([[3., 3.],
        [7., 7.]])

In [57]:
c @ d

tensor([[3., 3.],
        [7., 7.]])

In [58]:
c.matmul(d)

tensor([[3., 3.],
        [7., 7.]])

In [60]:
c.mm(d)

tensor([[3., 3.],
        [7., 7.]])

In [67]:
# 对于高维的Tensor(dim>2)，定义其矩阵乘法仅最后的两个维度，要求前面的维度必须保持一致，像矩阵的索引一样并且运算操只有torch.matmul()
e = torch.linspace(1, 8, 8).view(2, 2, 2)
e

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [68]:
f = torch.ones_like(e)
f

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [69]:
e @ f

tensor([[[ 3.,  3.],
         [ 7.,  7.]],

        [[11., 11.],
         [15., 15.]]])

## 幂运算

In [70]:
torch.pow(a, 2)

tensor([ 4.,  9., 16.])

In [71]:
a.pow(2)

tensor([ 4.,  9., 16.])

In [72]:
a**2

tensor([ 4.,  9., 16.])

In [73]:
a.pow_(2)

tensor([ 4.,  9., 16.])

In [74]:
a

tensor([ 4.,  9., 16.])

In [75]:
torch.exp(a)

tensor([5.4598e+01, 8.1031e+03, 8.8861e+06])

In [76]:
a.exp_()

tensor([5.4598e+01, 8.1031e+03, 8.8861e+06])

In [77]:
a

tensor([5.4598e+01, 8.1031e+03, 8.8861e+06])

## 开方运算

In [78]:
a.sqrt()

tensor([   7.3891,   90.0171, 2980.9580])

In [79]:
a.sqrt_()

tensor([   7.3891,   90.0171, 2980.9580])

In [80]:
a

tensor([   7.3891,   90.0171, 2980.9580])

## 对数运算

In [81]:
torch.log2(a)

tensor([ 2.8854,  6.4921, 11.5416])

In [82]:
torch.log10(a)

tensor([0.8686, 1.9543, 3.4744])

In [83]:
torch.log(a)

tensor([2.0000, 4.5000, 8.0000])

In [84]:
torch.log_(a)

tensor([2.0000, 4.5000, 8.0000])

In [85]:
a

tensor([2.0000, 4.5000, 8.0000])