可广播的一对张量需满足以下规则：
每个张量至少有一个维度。
迭代维度尺寸时，从尾部的维度开始，维度尺寸
​ 或者相等，
​ 或者其中一个张量的维度尺寸为 1 ，
​ 或者其中一个张量不存在这个维度。

In [1]:
import torch

In [15]:
# 相同维度，一定可以 broadcasting
x=torch.ones(5,7,3)
y=torch.ones(5,7,3)
x+y, (x+y).shape

(tensor([[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],
 
         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],
 
         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],
 
         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],
 
         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]),
 torch.Size([5, 7, 3]))

In [6]:
# x和y不能被广播,因为x没有符合“至少有一个维度”，所以不可以broadcasting
x=torch.ones(0)
y=torch.ones(5,7)
x+y

RuntimeError: The size of tensor a (0) must match the size of tensor b (7) at non-singleton dimension 1

In [14]:
# x 和 y 可以广播
x=torch.ones(5,3,4,1)
y=torch.ones(  3,1,1)
# 从尾部维度开始遍历
# 1st尾部维度: x和y相同，都为1。
# 2nd尾部维度: y为1，x为4,符合维度不等且其中一个维度为1，则广播为4。
# 3rd尾部维度: x和y相同，都为3。
# 4th尾部维度: y维度不存在，x为5,符合维度不等且其中一个维度不存在，则广播为5。
x+y, (x+y).shape

(tensor([[[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.

In [11]:
# x 和 y 不可以广播，因为3rd尾部维度x为2,y为3,不符合维度不等且其中一个维度为1。
x=torch.ones(5,2,4,1)
y=torch.ones(  3,1,1)
x+y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [13]:
# x 和 y 可以广播，在维度较小y前面增加维度，使它们维度相等。
x=torch.ones(5,2,4,1)
y=torch.ones(1,1)
x+y, (x+y).shape

(tensor([[[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]],
 
 
         [[[2.],
           [2.],
           [2.],
           [2.]],
 
          [[2.],
           [2.],
           [2.],
           [2.]]]]),
 torch.Size([5, 2, 4, 1]))