/ .floor() 向下取整数
/ .ceil() 向上取整数
/ .round() 四舍五入 > ： 0 · 5 向上取整 ， < 0 · 5 向下取整
/ .trunc() 裁剪 ， 只取整数部分
/ .frac() 只取小数部分
/ ％ 取余

In [2]:
import torch

In [4]:
a = torch.rand(10).view(2, 5) * 10
a

tensor([[0.9221, 6.3668, 5.5329, 3.2131, 6.2256],
        [1.3706, 6.7182, 8.1761, 4.5896, 6.4551]])

In [5]:
# 向下取整
torch.floor(a)

tensor([[0., 6., 5., 3., 6.],
        [1., 6., 8., 4., 6.]])

In [6]:
# 向上取整
torch.ceil(a)

tensor([[1., 7., 6., 4., 7.],
        [2., 7., 9., 5., 7.]])

In [8]:
# 四舍五入
torch.round(a)

tensor([[1., 6., 6., 3., 6.],
        [1., 7., 8., 5., 6.]])

In [10]:
# 取整数部分
torch.trunc(a)

tensor([[0., 6., 5., 3., 6.],
        [1., 6., 8., 4., 6.]])

In [12]:
# 取余数部分
a % 1

tensor([[0.9221, 0.3668, 0.5329, 0.2131, 0.2256],
        [0.3706, 0.7182, 0.1761, 0.5896, 0.4551]])