

/ torch ge(input, other, out=None)
# input>= other
/ torch.gt(input, other, out=None)
# input>other
/ torch 」 e(input, other, out=None)
# input=<other
/ torch 」 t(inputl other, out=None)
# input<other
/ torch.ne(input, Other, out=None) # input ！ = other 不等于

torch.sort(input, dim=None, descending=FaIse, out=None) # 对
目标 input 进行排序
torch.topk(inputl k, dim=Nonel largest=True, sorted=True,
out=None) # 沿着指定维度返回最大 k 个数值及其索引值
torch.kthvalue(input, k, dim=None, out=None)
# 沿着指定维度返回第 k 个最小值及其索引值

torch.isfinite(tensor) / torch.isinf(tensor) / torch.isnan(tensor)
返回一个标记元素是否为 finite/inf/nan 的 mask 张量 。


In [1]:
import numpy as np
import torch

In [4]:
a = torch.linspace(1, 9, 9).view(3, 3)
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [5]:
b = torch.ones_like(a) * 5
b

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

## torch.eq()

In [6]:
# torch.eq(input, other, out=None) # 按成员进行等式操作，相同返回True
torch.eq(a, b)

tensor([[False, False, False],
        [False,  True, False],
        [False, False, False]])

## torch.equal()

In [7]:
# torch.equal(tensor1, tensor2) # 如果tensor1和tensor2有相同的size和elements，则为true
torch.equal(a, b)

False

## torch.ge()

In [10]:
# a大于等于b
torch.ge(a, b)

tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])

## torch.gt()

In [11]:
# a大于b
torch.gt(a, b)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

## torch.le()

In [13]:
# a小于等于b
torch.le(a, b)

tensor([[ True,  True,  True],
        [ True,  True, False],
        [False, False, False]])

## torch.lt()

In [15]:
# a小于等于b
torch.lt(a, b)

tensor([[ True,  True,  True],
        [ True, False, False],
        [False, False, False]])

## torch.ne()

In [17]:
# a中哪个元素不等于b
torch.ne(a, b)

tensor([[ True,  True,  True],
        [ True, False,  True],
        [ True,  True,  True]])

## torch.sort()

In [18]:
# 生成随机乱序序号
c = torch.randperm(10)
c

tensor([3, 7, 2, 8, 1, 5, 6, 0, 9, 4])

In [20]:
# 对Tensor进行排序并返回排序索引
torch.sort(c)

torch.return_types.sort(
values=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
indices=tensor([7, 4, 2, 0, 9, 5, 6, 1, 3, 8]))

In [21]:
values, indices = torch.sort(c)

In [22]:
values

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
indices

tensor([7, 4, 2, 0, 9, 5, 6, 1, 3, 8])

In [25]:
torch.sort(c, descending=True)  # 降序

torch.return_types.sort(
values=tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
indices=tensor([8, 3, 1, 6, 5, 9, 0, 2, 4, 7]))

In [26]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [29]:
torch.sort(a, dim=1, descending=True)  # 对某个维度排序

torch.return_types.sort(
values=tensor([[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]]),
indices=tensor([[2, 1, 0],
        [2, 1, 0],
        [2, 1, 0]]))

In [31]:
torch.sort(a, dim=0, descending=True)  # 对某个维度排序

torch.return_types.sort(
values=tensor([[7., 8., 9.],
        [4., 5., 6.],
        [1., 2., 3.]]),
indices=tensor([[2, 2, 2],
        [1, 1, 1],
        [0, 0, 0]]))

## torch.topk()

In [40]:
torch.topk(a, k=1)  # 返回0维中前k个最大的数，默认dim=1

torch.return_types.topk(
values=tensor([[3.],
        [6.],
        [9.]]),
indices=tensor([[2],
        [2],
        [2]]))

In [41]:
torch.topk(a, k=1, dim=0)

torch.return_types.topk(
values=tensor([[7., 8., 9.]]),
indices=tensor([[2, 2, 2]]))

## torch.kthvalue()

In [44]:
torch.kthvalue(a, k=2)  # 返回某1维上排序后的第k个数字

torch.return_types.kthvalue(
values=tensor([2., 5., 8.]),
indices=tensor([1, 1, 1]))

In [45]:
torch.kthvalue(a, k=2, dim=0)

torch.return_types.kthvalue(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))

## torch.isfinite()

In [46]:
torch.isfinite(a)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [47]:
torch.isfinite(a/0)  # 是否有界

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

## torch.isinf()

In [48]:
torch.isinf(a)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [50]:
torch.isinf(a/0)  # 是否无界

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## torch.isnan()

In [51]:
torch.isnan(a)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [52]:
torch.isnan(a)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [55]:
import numpy as np

torch.isnan(a/np.nan)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])