/ torch.abs(input, out=None)
/ torch.acos(input, out=None)
/ torch.asin(inputl out=None)
/ torch.atan(input, out=None)
/ torch.atan2(input, inpu2,out=None)
/ torch.cos(inputl out=None)
/ torch.cosh(input, out=None)
/ torch.sin(inputl out=None)
/ torch.sinh(input, out=None)
/ torch.tan(input, out=None)
/ torch.tanh(input, out=None)

In [1]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
torch.cos(a)

tensor([0.5403, 0.5403, 0.5403])

In [5]:
b = torch.zeros_like(a)
b

tensor([0., 0., 0.])

In [6]:
torch.cos(b)

tensor([1., 1., 1.])

In [9]:
import math

c = torch.ones(3)* math.pi
c

tensor([3.1416, 3.1416, 3.1416])

In [10]:
torch.cos(c)

tensor([-1., -1., -1.])