In [1]:
import torch

In [3]:
a = torch.linspace(1, 9, 9).view(3, 3)
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

## torch.mean()

In [5]:
torch.mean(a)

tensor(5.)

In [7]:
torch.mean(a, dim=0)

tensor([4., 5., 6.])

In [8]:
torch.mean(a, dim=1)

tensor([2., 5., 8.])

## torch.sum()

In [9]:
torch.sum(a, dim=1)

tensor([ 6., 15., 24.])

## torch.prod()

In [12]:
torch.prod(a)  # 连乘

tensor(362880.)

In [13]:
torch.prod(a, dim=1)

tensor([  6., 120., 504.])

## torch.argmax()

In [14]:
torch.argmax(a, dim=1)

tensor([2, 2, 2])

## torch.argmin()

In [16]:
torch.argmin(a, dim=1)

tensor([0, 0, 0])

## torch.std()

In [17]:
torch.std(a)

tensor(2.7386)

In [18]:
torch.std(a, dim=1)

tensor([1., 1., 1.])

## torch.var()

In [19]:
torch.var(a)

tensor(7.5000)

## torch.median()

In [20]:
torch.median(a)

tensor(5.)

## torch.mode()

In [22]:
torch.mode(a)

torch.return_types.mode(
values=tensor([1., 4., 7.]),
indices=tensor([0, 0, 0]))

## torch.histc()

In [26]:
torch.histc(a, 9)  # 直方图

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

## torch.bincount()

In [33]:
b = torch.randint(0, 10, [10])
b

tensor([5, 1, 5, 2, 2, 9, 2, 8, 0, 3])

In [35]:
torch.bincount(b)  # 针对非负整数Tensor计数

tensor([1, 1, 3, 1, 0, 2, 0, 0, 1, 1])